### ISSUE TITLE
Expected UI issues with Wagtail 3.0 release

### ISSUE THREAD

**Issue by thibaudcolas** [spapas/wagtail-multi-upload#10]
Hi @spapas! The [Wagtail 3.0 first release candidate](https://github.com/wagtail/wagtail/discussions/8362) is out. There are large UI changes in this release, for which we have [reviewed expected breakage in third-party UI customisations](https://github.com/wagtail/wagtail/discussions/7739#discussioncomment-2615089).

This is beyond what we do with our normal breaking changes policy, since the majority of those changes are on parts of Wagtail that haven’t been publicly supported / documented in any way. To make sure this goes smoothly anyway, I’m here to provide an advance notice of what we’re aware of with this specific package 🙂 

In the case of this package we’re only expecting one issue:

```
wagtail/spapas/wagtail-multi-upload/wagtail_multi_upload/templates/wagtail_multi_upload/edit_handlers/custom_inline_panel.html
18:        {% include "wagtailadmin/edit_handlers/inline_panel_child.html" %}
26:{% include "wagtailadmin/edit_handlers/inline_panel_child.html" with child=self.empty_child %}
```

This template has moved to `wagtailadmin/panels/inline_panel_child.html`. That’s about it!

---

I hope this all makes sense. We’ve made a lot of other styling and template changes that are hard to track down, and for which it’s unclear whether any breakage might be expected or not. As you go through the Wagtail 3.0 compatibility work, please let me know if there are other compatibility issues you come across so we can consider those customisations in Wagtail development in the future, and let others know about those breakages.

**Comment by spapas** [comment]
Hey @thibaudcolas thanks for the heads up! It's great that you inform package maintainers about possible issues with the next version of wagtail; the major blocker for updating to new versions of wagtail (and django of course) is non-updated packages :)

I'm going to try installing wagtail 3.0 next week on my dev env and handle this and any other compatibility issues.

Kind regards,
Serafeim

**Comment by thibaudcolas** [comment]
Glad you’re liking it! This is indeed exactly why we’re doing this, and why we now have the #package-maintainers channel on Slack. Note so far we’re only providing a heads up for things that aren’t officially supported – for everything else, we expect people to look at the release notes and identify compatibility issues themselves. I hope we’ll hear from other package maintainers as well on how this is working out.

**Comment by spapas** [comment]
Hello @thibaudcolas unfortunately I don't have the time nor the mood to do the update to wagtail 3.x. Please see the relevant discussion [here](https://wagtailcms.slack.com/archives/C81FGJR2S/p1651557532880859)

It seems that there are very big changes in wagtail 3.x related to how admin components are implemented and it would be a real PITA for me to update this. I have some power over the editors so my decision is to stay to 2.x as long as possible and if we update to 3.x then we won't have multiple image uploads 👎 

I'd be happy to accept a PR with the fix of course (it doesn't even need to be compatible with wagtail 2.x) but I don't have high hopes that anybody would want to do that penal labour to fix this 😱

**Comment by spapas** [comment]
I have also updated the README to reflect that: https://github.com/spapas/wagtail-multi-upload/blob/master/README.md#warning-this-package-does-not-support-wagtail-3x-because-of-the-changes-needed-to-upgrade-i-will-keep-supporting-wagtail-2x-as-long-as-possible-though

**Comment by thibaudcolas** [comment]
Fair call! It’ll be interesting to see how the upgrade goes for other projects with panel / edit handler customisations. I wasn’t involved with those changes myself and it’s not an API I’m very familiar with so I don’t understand the scale of the changes we made, and whether they’re mostly to public / documented APIs or private things too.

**Comment by spapas** [comment]
I'm not sure about the others but my understanding is that this one is very hacky... Also notice that this package is not my original work but a re-packaging of rajeev's great work on this PR: https://github.com/wagtail/wagtail/pull/4393 so I'm not very familiar with all the nuts and bolts of this :|

My only hope is that somebody is using this package and needs to upgrade to wagtail 3.x so he is forced to pick it up 😈

**Comment by spapas** [comment]
This has been fixed!
