### ISSUE TITLE
Support with wagtail-modeltranslation

### ISSUE THREAD

**Issue by olivierdalang** [spapas/wagtail-multi-upload#5]
Hi !

Currently, wagtail-multi-upload and wagtail-modeltranslation don't play nice together.

1. By default, wagtail-modeltranslation doesn't recognize the custom inline panels. I've made a PR for this in wagtail-modeltranslation, see : https://github.com/infoportugal/wagtail-modeltranslation/pull/323

2. Once recognized, it doesn't hide the translated fields for images added in batch, because some event isn't triggered in a similar way to the regular "Add" button. It's okay-ish when there's just 2-3 languages, but when there's more, it makes the form unusable.

It seems wagtail-modeltranslations installs a listener like this :
```javascript
/**
 * Adds event listeners on click for inlines.
*/
$('a[id^=id_][id$=-ADD]').click(e => {
 ...
});
```
So as a hack, we could trigger the add button click listeners : 
```javascript
$.each($._data($('#id_resource_images-ADD')[0], 'events')['click'], (i,o)=>o.handler(new Event(null)));
```

**Comment by olivierdalang** [comment]
Closing this, as it actually makes more sense to fix 2. on wagtail-modeltranslation too (see https://github.com/infoportugal/wagtail-modeltranslation/pull/324)

**Comment by spapas** [comment]
Excellent thank you very much!
