### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by nicksergeant** [spapas/wagtail-multi-upload#9]
I just wanted to say thanks for this package. Not being able to upload multiple images directly into a page object is really frustrating for some of my customers who use the Wagtail admin.

As I think I'll be heavily using this across several projects, I will see if I can get drag-and-drop (#1) working, as well as supporting multiple `MultipleImagesPanel` (#6) on a single page working in the future.

Thanks, again!

(feel free to close this issue)

**Comment by spapas** [comment]
Thank you for your kind words, any help is greatly appreciated!
